# Generated by Django 4.1.1 on 2022-09-23 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediosP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valorApagar', models.IntegerField()),
                ('efectivo', models.BooleanField(default=True)),
                ('tarjeta_debito', models.BooleanField(default=False)),
                ('tarjeta_credito', models.BooleanField(default=False)),
                ('pse', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediosP', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
